# NumPy Arrays

In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]
myarray = np.array(mylist)
type(myarray)

numpy.ndarray

In [ ]:
myarray

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
my_matrix = np.array(my_matrix)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(5) #floating point 0 are returned

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,5)) #2 dimensional np array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,num=20) #returns evenly spaced numbers over specified interval

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0,10,10,endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.eye(5) #creates identity matrix 

#only single number is passed bcoz identity matrix is symmetric matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2,3) #returns random numbers of given shape

array([[0.60082799, 0.95566629, 0.56638332],
       [0.1788049 , 0.42291358, 0.33835374]])

In [ ]:
np.random.randn(10) #creates samples from a "standard normal distribution" - mean=0 and sd=1

array([-1.35554522, -1.70674931, -0.07971384, -0.14499872,  0.1014712 ,
        1.0281876 , -0.03701354, -0.83461742,  0.96165253,  1.08239451])

In [ ]:
np.random.randn(2,3)

array([[ 1.30439566,  0.64033624, -0.43204692],
       [-1.2906428 ,  1.73103297, -0.72332479]])

In [ ]:
np.random.randint(0,101,5) #returns random integers

array([48, 75,  0, 73, 33])

In [ ]:
np.random.randint(0,101,(3,3))

array([[61, 21, 61],
       [15, 71, 15],
       [41, 14, 62]])

In [ ]:
np.random.seed(42) #mostly 42 with reference to Hitchhiker's guide to the galaxy book
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
#used to repeat random numbers to test different models, or visualizations

In [ ]:
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
randomarray = np.random.randint(0,101,10)

In [ ]:
randomarray

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [ ]:
randomarray.max()

99

In [ ]:
randomarray.min()

2

In [ ]:
randomarray.argmax() #returns the index of the location of the maximum element

5

In [ ]:
randomarray.argmin()

7

In [ ]:
randomarray.dtype

dtype('int64')

In [ ]:
randomarray.shape

(10,)

In [ ]:
r = randomarray.reshape(2,5)

In [ ]:
r.max()

99

In [ ]:
r.shape

(2, 5)

In [ ]:
#TASK1

myarray = np.linspace(0,10,num=101)

In [ ]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

**NumPy indexing and selection**

In [ ]:
import numpy as np

arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:4]

array([1, 2, 3])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#Broadcasting

arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
#Slicing a section of array and setting it to new variable
arr2 = arr[0:5]

In [ ]:
arr2

array([0, 1, 2, 3, 4])

In [ ]:
cpy = arr.copy()

In [ ]:
cpy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[0]

array([ 5, 10, 15])

In [ ]:
arr_2d[1][1]

25

In [ ]:
arr_2d[1,1]

25

In [ ]:
arr_2d[:2,1:] #getting a sub section of matrix

array([[10, 15],
       [25, 30]])

In [ ]:
#conditional selection

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#Coding exercise 2

dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])


In [ ]:
rolls_greater2 = dice_rolls[dice_rolls>2]

In [ ]:
rolls_greater2

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [ ]:
total_rolls_over_two = len(dice_rolls[dice_rolls>2])

In [ ]:
total_rolls_over_two

19

**NumPy Operations**

In [ ]:
import numpy as np

arr = np.arange(0,10)

In [ ]:
arr + 5 #performs elementwise addition 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr / arr 

<ipython-input-37-5dd38c744e6f>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#divsion by zero will give a warning in numpy but still output the result

In [ ]:
1 / 0

ZeroDivisionError: ignored

In [ ]:
#normal python gives error on division by zero

In [ ]:
1 / arr

<ipython-input-40-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
#again a warning in case of divison by zero

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

<ipython-input-43-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
#log 0 gives warning

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.max()

9

In [ ]:
arr.var() #variance

8.25

In [ ]:
arr.std() #standard deviation

2.8722813232690143

In [ ]:
arr2d = np.arange(0,25).reshape(5,5)

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d.sum()

300

In [ ]:
#sum of rows or sum of columns

arr2d.sum(axis=0) #performs the operations across the rows i.e. sum of columns

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis=1) #performs the operations across the columns i.e. sum of rows

array([ 10,  35,  60,  85, 110])